android.builtInKotlin=false
android.dependency.useConstraints=true
android.enableJetifier=false
android.newDsl=false
android.nonTransitiveRClass=true
android.useAndroidX=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx3g
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false