---
name: "🛠️ Feature Request"
description: "Request a new feature"
title: "Feature: "
labels:
  - "feature_request"
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to fill out this feature request and helping us improve!**
        Kindly search to see if a similar issue [already exists](https://github.com/anwilli5/coin-collection-android-US/issues) for your feature.

        We are also happy to accept contributions from our users. For more details see [here](https://github.com/anwilli5/coin-collection-android-US/blob/main/CONTRIBUTING.md).

  - type: textarea
    id: problem-motivation
    validations:
      required: true
    attributes:
      label: "💡 Problem / Motivation"
      description: "Describe the problem or need this feature would address. Why is this valuable?"
  - type: textarea
    id: proposed-solution
    validations:
      required: true
    attributes:
      label: "🚀 Proposed Solution"
      description: "Describe the solution you'd like to see implemented."
  - type: textarea
    id: alternatives-considered
    validations:
      required: false
    attributes:
      label: "🔄 Alternatives Considered"
      description: "Have you considered any alternative solutions or workarounds? If so, describe them here."
