---
name: "🛠️ Feature Request"
description: "Request a new feature"
title: "Feature: "
labels:
  - "feature_request"
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to fill out this feature request and helping us improve!**
        Kindly search to see if a similar issue [already exists](https://github.com/anwilli5/coin-collection-android-US/issues) for your feature.

        We are also happy to accept contributions from our users. For more details see [here](https://github.com/anwilli5/coin-collection-android-US/blob/main/CONTRIBUTING.md).

  - type: textarea
    id: feature-description
    validations:
      required: true
    attributes:
      label: "🚀 Feature Proposal"
      description: "Clearly describe the feature you're proposing. Explain the problem it solves and why it would be valuable. If you've considered alternative solutions or workarounds, please mention them too."
