name: "Create New Issue"
description: "Report a new issue"
title: "Issue: "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to create an issue! Your contribution helps us improve. Please provide as much detail as possible to help us understand and resolve the problem quickly. If you are reporting a bug, please include:

        *   Clear steps to reproduce the issue.
        *   What you expected to happen.
        *   What actually happened.
        *   Any error messages.
        *   Your environment (e.g., app version, OS version).
  - type: textarea
    id: issue-description
    validations:
      required: true
    attributes:
      label: "💭 Description"
      description: "A clear and concise description of what the issue is."
